# Generated by Django 3.2.5 on 2022-11-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_payment_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeType',
            new_name='Offering',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='dhehebu_alilookolea',
            new_name='dhehebu_alikookokea',
        ),
        migrations.AddField(
            model_name='member',
            name='namba_ya_zaka',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
