# Generated by Django 3.2.5 on 2022-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20221126_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ameajiriwa',
            field=models.CharField(choices=[('Ameajiriwa', 'Ameajiriwa'), ('Amejiajiri', 'Amejiajiri'), ('Hana Kazi', 'Hana Kazi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='ameoa_ameolewa',
            field=models.CharField(choices=[('Ameoa', 'Ameoa'), ('Ameolewa', 'Ameolewa'), ('Hajaolewa', 'Hajaolewa'), ('Hajaoa', 'Hajaoa')], max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='maji_mengi',
            field=models.CharField(choices=[('Maji Mengi', 'Maji Mengi'), ('Maji Kidogo', 'Maji Kidogo')], max_length=200),
        ),
    ]
