# Generated by Django 3.2 on 2024-03-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_anatoa_zaka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='feetype',
        ),
        migrations.AddField(
            model_name='offering',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.offering'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='member.member'),
        ),
    ]
