# Generated by Django 3.2.5 on 2024-03-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20240327_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zakas', to='member.member')),
            ],
        ),
    ]
